concierge/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import RegexURLPattern, RegexURLResolver
from django.views.decorators.clickjacking import xframe_options_exempt
from oauth2_provider import views as oauth2_views
from saml import views as saml_views
from api import views as api_views
from django.contrib import admin
from core import views
from core.class_views import PleioLoginView, PleioSessionDeleteView, PleioSessionDeleteOtherView
from django.views.i18n import JavaScriptCatalog

class DecoratedURLPattern(RegexURLPattern):
    def resolve(self, *args, **kwargs):
        result = super(DecoratedURLPattern, self).resolve(*args, **kwargs)
        if result:
            result.func = self._decorate_with(result.func)
        return result


class DecoratedRegexURLResolver(RegexURLResolver):
    def resolve(self, *args, **kwargs):
        result = super(DecoratedRegexURLResolver, self) \
            .resolve(*args, **kwargs)
        if result:
            result.func = self._decorate_with(result.func)
        return result


def decorated_includes(func, includes):
    """
    Include URLconf from module but apply the specified decorator to each.
    """
    urlconf_module, app_name, namespace = includes
    urlconf_urls = urlconf_module.urlpatterns

    for item in urlconf_urls:
        if isinstance(item, RegexURLPattern):
            item.__class__ = DecoratedURLPattern
            item._decorate_with = func

        elif isinstance(item, RegexURLResolver):
            item.__class__ = DecoratedRegexURLResolver
            item._decorate_with = func

    return urlconf_module, app_name, namespace


legacy_urls = [
    url(r'^mod/profile/icondirect.php$', views.avatar, name='avatar_legacy'),
    url(r'^action/logout$', views.logout, name='logout_legacy')
]

urls = [
    url(r'^register/$', views.register, name='register'),
    url(r'^register/complete/$', views.register_complete, name='register_complete'),
    url(r'^register/activate/(?P<activation_token>[-:\w]+)/$', views.register_activate, name='register_activate'),
    url(r'^change-email/$', views.change_email, name='change_email'),
    url(r'^change-email/activate/(?P<activation_token>[-:\w]+)/$', views.change_email_activate, name='change_email_activate'),
    url(r'^legal-pages/(?P<page_name>[\w-]+)/$', views.legal_pages, name='legal_pages'),
    url(r'^legal-pages/(?P<page_name>[\w-]+)/(?P<language_code>[\w-]+)/$', views.legal_pages, name='legal_pages'),
    url(r'^securitypages/(?P<page_action>[\w-]+)/$', views.security_pages, name='security_pages'),
    url(r'^securitypages/$', views.security_pages, name='security_pages'),
    url(r'^password_reset/$', auth_views.password_reset, { 'template_name': 'password_reset.html', 'subject_template_name': 'emails/reset_password_subject.txt', 'email_template_name': 'emails/reset_password.txt', 'html_email_template_name': 'emails/reset_password.html' }, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, { 'template_name': 'password_reset_done.html' }, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, { 'template_name': 'password_reset_confirm.html' }, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, { 'template_name': 'password_reset_complete.html' }, name='password_reset_complete'),
    url(r'^login/(?P<login_step>[\w-]+)/$', PleioLoginView.as_view(), name='login'),
    url(r'^login/$', PleioLoginView.as_view(), name='login'),
    url(r'^get_user_and_idp/$', views.get_user_and_idp, name='get_user_and_idp'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^delete-account/$', views.delete_account, name='delete_account'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^account/sessions/other/delete/$', view=PleioSessionDeleteOtherView.as_view(), name='session_delete_other'),
    url(r'^account/sessions/(?P<pk>\w+)/delete/$', view=PleioSessionDeleteView.as_view(), name='session_delete'),
    url(r'^oauth/v2/authorize$', oauth2_views.AuthorizationView.as_view(), name='authorize'),
    url(r'^oauth/v2/token$', oauth2_views.TokenView.as_view(), name='token'),
    url(r'^oauth/v2/revoke_token$', oauth2_views.RevokeTokenView.as_view(), name='revoke-token'),
    url(r'^api/users/me$', api_views.me, name='me'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home')
]

tf_urls = [
    url(r'', include('two_factor.urls', 'two_factor'))
]
us_urls = [
    url(r'', include('user_sessions.urls', 'user_sessions'))
]
oidc_urls = [
    url(r'^openid/', decorated_includes(
      xframe_options_exempt,
      include('oidc_provider.urls', namespace='oidc_provider')
    ))
]
django_urls = [
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]
saml_urls = [
    #url(r'^saml/$', saml_views.saml, name='saml'),
    url(r'^saml/sso/(?P<idp_shortname>[\w-]+)/$', saml_views.sso, name='saml_sso'),
    url(r'^saml/acs/$', saml_views.acs, name='saml_acs'),
    #url(r'^saml/slo/(?P<SAMLResponse>[\w-]+)/$', saml_views.slo, name='saml_slo'),
    url(r'^saml/slo/$', saml_views.slo, name='saml_slo'),
    url(r'^saml/attrs/$', saml_views.attrs, name='saml-attrs'),
    url(r'^saml/metadata/$', saml_views.metadata, name='saml-metadata'),
    url(r'^saml/connect/$', saml_views.connect_and_login, name='saml-connect'),
    url(r'^saml/set_new_password/(?P<activation_token>[-:\w]+)/$', saml_views.set_new_password, name='set_new_password'),
    url(r'^saml/connections/$', saml_views.show_connections, name='saml_connections'),
    url(r'^saml/connection_delete/(?P<pk>\w+)/$', saml_views.delete_connection, name='saml_connection_delete'),
]
urlpatterns = legacy_urls + urls + tf_urls + us_urls + oidc_urls + django_urls + saml_urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pleio_account/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import RegexURLPattern, RegexURLResolver
from django.views.decorators.clickjacking import xframe_options_exempt
from oauth2_provider import views as oauth2_views
from api import views as api_views
from django.contrib import admin
from core import views
from core.class_views import PleioLoginView, PleioSessionDeleteView, PleioSessionDeleteOtherView
from django.views.i18n import JavaScriptCatalog


class DecoratedURLPattern(RegexURLPattern):
    def resolve(self, *args, **kwargs):
        result = super(DecoratedURLPattern, self).resolve(*args, **kwargs)
        if result:
            result.func = self._decorate_with(result.func)
        return result


class DecoratedRegexURLResolver(RegexURLResolver):
    def resolve(self, *args, **kwargs):
        result = super(DecoratedRegexURLResolver, self) \
            .resolve(*args, **kwargs)
        if result:
            result.func = self._decorate_with(result.func)
        return result


def decorated_includes(func, includes):
    """
    Include URLconf from module but apply the specified decorator to each.
    """
    urlconf_module, app_name, namespace = includes
    urlconf_urls = urlconf_module.urlpatterns

    for item in urlconf_urls:
        if isinstance(item, RegexURLPattern):
            item.__class__ = DecoratedURLPattern
            item._decorate_with = func

        elif isinstance(item, RegexURLResolver):
            item.__class__ = DecoratedRegexURLResolver
            item._decorate_with = func

    return urlconf_module, app_name, namespace


legacy_urls = [
    url(r'^mod/profile/icondirect.php$', views.avatar, name='avatar_legacy'),
    url(r'^action/logout$', views.logout, name='logout_legacy')
]

urls = [
    url(r'^register/$', views.register, name='register'),
    url(r'^register/complete/$', views.register_complete, name='register_complete'),
    url(r'^register/activate/(?P<activation_token>[-:\w]+)/$', views.register_activate, name='register_activate'),
    url(r'^change-email/$', views.change_email, name='change_email'),
    url(r'^change-email/activate/(?P<activation_token>[-:\w]+)/$', views.change_email_activate, name='change_email_activate'),
    url(r'^termsofuse/$', views.terms_of_use, name='terms_of_use'),
    url(r'^securitypages/(?P<page_action>[\w-]+)/$', views.security_pages, name='security_pages'),
    url(r'^securitypages/$', views.security_pages, name='security_pages'),
    url(r'^password_reset/$', auth_views.password_reset, { 'template_name': 'password_reset.html', 'subject_template_name': 'emails/reset_password_subject.txt', 'email_template_name': 'emails/reset_password.txt', 'html_email_template_name': 'emails/reset_password.html' }, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, { 'template_name': 'password_reset_done.html' }, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, { 'template_name': 'password_reset_confirm.html' }, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, { 'template_name': 'password_reset_complete.html' }, name='password_reset_complete'),
    url(r'^login/(?P<login_step>[\w-]+)/$', PleioLoginView.as_view(), name='login'),
    url(r'^login/$', PleioLoginView.as_view(), name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^account/sessions/other/delete/$', view=PleioSessionDeleteOtherView.as_view(), name='session_delete_other'),
    url(r'^account/sessions/(?P<pk>\w+)/delete/$', view=PleioSessionDeleteView.as_view(), name='session_delete'),
    url(r'^oauth/v2/authorize$', oauth2_views.AuthorizationView.as_view(), name='authorize'),
    url(r'^oauth/v2/token$', oauth2_views.TokenView.as_view(), name='token'),
    url(r'^oauth/v2/revoke_token$', oauth2_views.RevokeTokenView.as_view(), name='revoke-token'),
    url(r'^api/users/me$', api_views.me, name='me'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home')
]

tf_urls = [
    url(r'', include('two_factor.urls', 'two_factor'))
]
us_urls = [
    url(r'', include('user_sessions.urls', 'user_sessions'))
]
oidc_urls = [
    url(r'^openid/', decorated_includes(
      xframe_options_exempt,
      include('oidc_provider.urls', namespace='oidc_provider')
    ))
]
django_urls = [
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

urlpatterns = legacy_urls + urls + tf_urls + us_urls + oidc_urls + django_urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

emailvalidator/models.py
"""
Model definitions for emailvalidator
"""
from django.db import models


class EmailDomainGroup(models.Model):
    """
    Naming of groups of regex patterns
    """
    name = models.CharField(max_length=255)


class EmailRegExValidator(models.Model):
    """
    Regex patterns
    """
    name = models.CharField("Name", max_length=255, null=True)
    regex = models.CharField("Regex/domain", max_length=100)
    allow_all = models.BooleanField("Allow all from domain", default=False)
    group = models.ForeignKey(EmailDomainGroup)

saml/forms.py
from django.utils.translation import gettext, gettext_lazy as _
from django.contrib.auth import password_validation
from django.conf import settings
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate 
from django.contrib.auth.forms import AuthenticationForm
from two_factor.forms import AuthenticationTokenForm, TOTPDeviceForm
from two_factor.utils import totp_digits, default_device
from core.models import User
from saml.models import IdentityProvider, ExternalId
from django.forms import Form

class SetPasswordForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(SetPasswordForm, self).__init__(*args, **kwargs)

    error_messages = {
        'invalid_password': _("The password is invalid."),
        'password_mismatch': _("The two password fields didn't match."),
    }

    new_password1 = forms.CharField(strip=False, widget=forms.PasswordInput(attrs={'autofocus': True}))
    new_password2 = forms.CharField(strip=False, widget=forms.PasswordInput)

    def clean_new_password2(self):
        new_password1 = self.cleaned_data.get("new_password1")
        new_password2 = self.cleaned_data.get("new_password2")

        if new_password1 and new_password2 and new_password1 != new_password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )

        password_validation.validate_password(self.cleaned_data.get('new_password2'))
        return new_password2


class ShowConnectionsForm(forms.ModelForm):
    class Meta:
        model = ExternalId
        fields = ('identityproviderid', 'externalid')

core/templates/backup_tokens.html
{% extends "base_account.html" %}
{% load i18n %}

{% block content %}
<h2>{% trans "Backup Tokens" %}</h2>
 <form method="post">{% csrf_token %}{{ form }}
     <div class="account__cards">
         <div class="card ___nopadding">
            <h2 class="card__title ___addpadding-side">{% block title %}{% trans "Backup tokens" %}{% endblock %}</h2>
            <div class="___addpadding-side">
                <p>{% blocktrans %}Backup tokens can be used when your primary and backup
                    phone numbers aren't available. The backup tokens below can be used
                    for login verification. If you've used up all your backup tokens, you
                    can generate a new set of backup tokens. Only the backup tokens shown
                    below will be valid.{% endblocktrans %}</p>
                    {% if device.token_set.count %}
                    <ul class="___inline">
                        {% for token in device.token_set.all %}
                        <li>
                            <span class="badge ___tag grey">{{ token.token }}</span>
                        </li>
                        {% endfor %}
                    </ul>
                    <br />
                    <p>{% blocktrans %}Print these tokens and keep them somewhere safe.{% endblocktrans %}</p>
                    {% else %}
                    <p>{% trans "You don't have any backup codes yet." %}</p>
                    {% endif %}
                </div>
                <div class="card__action ___addpadding-side">
                    <button class="button ___clear" type="submit">{% trans "Generate tokens" %}</button>
                </div>
         </div>
     </div>
  </form>
{% endblock %}

core/templates/base.html
{% load i18n %}
{% load static %}
{% load render_bundle from webpack_loader %}
{% load Pleio_templatetags %}
{% load settings_value %}
{% get_current_language as LANGUAGE_CODE %}
{% settings_value 'SITE_FAVICON' as SITE_FAVICON %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% settings_value 'SITE_TITLE' %}</title>
        <meta name="viewport" content="width=device-width,height=device-height,user-scalable=no,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0">
        <link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
        <link rel="icon" href="{% static SITE_FAVICON %}">
        {% render_bundle "web" "css" %}
        <script src='https://www.google.com/recaptcha/api.js'></script>
    </head>
    <body>
        <div class="account-overlay">
            {% if request.COOKIES.partner_site_logo_url %}
                <div class="account-theme" data-bg="{{ request.COOKIES.partner_site_logo_url }}">

                    {% if request.COOKIES.partner_site_url %}
                        <a href={{ request.COOKIES.partner_site_url }} class="button ___white ___outline account__close">{{ request.COOKIES.partner_site_name }}</a>
                    {% endif %}
                </div>
            {% endif %}

            <div class="account">
                <div class="account__top-bar">
                    {% settings_value 'SITE_LOGO' as site_logo %}
                    <a class="navigation__logo" title="{% trans "Back to the homepage" %}" href="{% settings_value 'EXTERNAL_HOST' %}">{% include_asset site_logo %}</a>
                </div>

                <div class="account__slider">
                    <div class="account__content-container">
                        <div class="account__content">
                            {% block content %}{% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script src="https://www.google.com/recaptcha/api.js"></script>
        <script src="//code.jquery.com/jquery-3.1.1.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
        {% render_bundle "vendor" "js" %}
        {% render_bundle "web" "js" %}
    </body>
</html>

core/templates/delete_account.html
{% extends "base_account.html" %}
{% load user_sessions %}
{% load i18n %}
{% load Pleio_templatetags %}

{% block content %}

<h2>{% trans "Delete my account" %}</h2>


{% if messages %}
    {% for message in messages %}
        {% if 'success' in message.tags %}
            <ul class="messages correct">
                <li>
                    {% include_asset "icons/check.svg" %}
                    <div class="textcolor_primary">{% trans 'Success' %}</div>
                    <div class="textcolor_secondary">{{ message }}</div>
                </li>
            </ul>
        {% elif 'error' in message.tags %}
            <ul class="messages error">
                <li>
                    {% include_asset "icons/account-alert.svg" %}
                    <div class="textcolor_primary">{% trans 'Error' %}</div>
                    <div class="textcolor_secondary">{{ message }}</div>
                </li>
            </ul>
        {% endif %}
    {% endfor %}
{% endif %}        

<div class="account__cards">
        <div class="card ___nopadding">
            <h2 class="card__title ___addpadding-side">{% trans "Delete my account" %}</h2>
            
            <form method="post" action="/delete-account/">
                <div class="___addpadding-side">
                    {% csrf_token %} 
                    <div class="image__2fa __enable">
                            {% include_asset "icons/account-alert.svg" %}
                        </div>
                        <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
                        <p>{% blocktrans %}If you confirm your password, your account will be deleted. 
                            You have to register again if you would like to rejoin this site.{% endblocktrans %}</p>
                        <br>
                    <fieldset>
                        <ul class="messages error">
                            {% for error in form.non_field_errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                        
                        <div class="input-field">
                            <label for="id_old_password">{% trans "Current Password" %}</label>
                            {{ form.errors.old_password }}
                            {{ form.old_password }}
                            <span class="password__toggle">{% include_asset "icons/eye.svg" %}</span>            
                            <p class="capslock"></p>
                        </div>

                    </fieldset>
                </div>
        
                <div class="card__action ___addpadding-side">
                    <button name="change_password" type="submit" class="button ___active ___clear" value="submit">{% trans "Confirm" %}</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

core/templates/html_snippet_account.html
{% extends "base_account.html" %}
{% load i18n %}

{% block content %}

{{ html_snippet }}

{% endblock %}

core/templates/language.html

{% load i18n %}

<a href="{{ current_path }}" class="ui primary button compact" onclick="changeLanguage();" id='btn' title="{% trans "Change language" %}">
      {% if request.COOKIES.lang == 'en'%}
        <span aria-hidden="true">FR</span>
        <span class="invisible" lang="fr">Français</span>
      {% else %}
        <span aria-hidden="true">EN</span>
        <span class="invisible" lang="en">English</span>
      {% endif %}
    </a>

<script>
function getCookie(cname) {
    var name = cname + "=";
    var decodedCookie = decodeURIComponent(document.cookie);
    var ca = decodedCookie.split(';');
    for(var i = 0; i <ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0) == ' ') {
            c = c.substring(1);
        }
        if (c.indexOf(name) == 0) {
            return c.substring(name.length, c.length);
        }
    }
    return "";
}

function changeLanguage() {
    if (getCookie('lang') == 'en') {
        setCookie("lang", 'fr');
    } else {
        setCookie("lang", 'en');
    }
}

function setCookie(sName, sValue, oExpires, sPath, sDomain, bSecure) {
    var sCookie = sName + "=" + encodeURIComponent(sValue);
    if (oExpires) {
        sCookie += "; expires=" + oExpires.toGMTString();
    }
    if (sPath) {
        sCookie += "; path=" + sPath;
    }
    if (sDomain) {
        sCookie += "; domain=" + sDomain;
    }
    if (bSecure) {
        sCookie += "; secure";
    }
    document.cookie = sCookie;
}
</script>

core/templates/legal_text.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="account--terms">
  {{ legal_text }}
</div>

{% endblock %}

core/templates/profile.html
{% extends "base_account.html" %}
{% load i18n %}
{% load Pleio_templatetags %}
{% load show_government_badge %}
{% load settings_value %}

{% block title %}Login{% endblock %}

{% block content %}
    <h2>{% trans "Profile" %}</h2>

    {% if messages %}
      {% for message in messages %}
        {% if 'success' in message.tags %}
            <ul class="messages correct">
                <li>
                    {% include_asset "icons/check.svg" %}
                    {% if 'password' in message.tags %}
                        <div class="textcolor_primary">{% trans "Password changed" %}</div>
                        <div class="textcolor_secondary">{% trans "You can now login using your new password" %}</div>
                    {% elif 'email' in message.tags %}
                        <div class="textcolor_primary">{% trans "Email address changed" %}</div>
                        <div class="textcolor_secondary">{% trans "You can now login using your new email adress" %}</div>
                    {% elif 'profile' in message.tags %}
                        <div class="textcolor_primary">{% trans "Profile changed" %}</div>
                        <div class="textcolor_secondary">{% trans "Your profile has been changed" %}</div>
                    {% else %}
                        <div class="textcolor_primary">{% trans 'Success' %}</div>
                        <div class="textcolor_secondary">{{ message }}</div>
                    {% endif %}
                </li>
            </ul>
        {% elif 'error' in message.tags %}
            <ul class="messages error">
                <li>
                    {% include_asset "icons/account-alert.svg" %}
                    <div class="textcolor_primary">{% trans 'Error' %}</div>
                    <div class="textcolor_secondary">{{ message }}</div>
                </li>
            </ul>
        {% endif %}
      {% endfor %}
      <p></p>
    {% endif %}

        <form enctype="multipart/form-data" method="post" action=".">
        <div class="account__cards">
            <div class="card ___nopadding">
                {% csrf_token %}
                <h2 class="card__title ___addpadding-side">{% trans "Your details" %}</h2>

                <ul class="messages error">
                    {% for error in form.non_field_errors %}
                        <li>
                        {% include_asset "icons/account-alert.svg" %}
                        <div class="textcolor_primary">{% trans "Invalid email address." %}</div>
                        <div class="textcolor_secondary">{{ error }}</div>
                        </li>
                    {% endfor %}
                </ul>
                <p></p><p></p>

                <fieldset class="___addpadding-side">
                    <div class="input-field">
                        <label for="id_name">{% trans "Name" %}</label>
                        {{ form.errors.name }}
                        {{ form.name }}
                    </div>
                    <div class="input-field">
                        <label for="id_email">{% trans "Email" %}</label>
                        {{ form.errors.email }}
                        {{ form.email }}
                        {% show_government_badge form.email.value as show_badge %}
                        {% if show_badge %}
                            <span class="badge green __uppercase">{% include_asset "icons/check.svg" %}{% trans "Government" %}</span>
                        {% endif %}
                    </div>
                    {% if text_change_pending %}
                        <div>
                            {{ text_change_pending }}<b>{{ text_email }}</b><br>
                            {% trans "Please check your inbox to validate the change." %}<br>
                            {% trans "Click " %}<a href="{% url 'change_email' %}"><b>{% trans "here" %}</b></a> {% trans "to resend the confirmation e-mail." %}
                        </div>
                    {% endif %}
                    <div class="register__check">
                        {{ form.errors.receives_newsletter }}
                        {{ form.receives_newsletter }}
                        <label for="id_receives_newsletter">{% trans "Please subscribe me to the " %}{% settings_value 'SITE_TITLE' %}{% trans " newsletter." %}</label>
                    </div>

            </fieldset>
                <div class="card__action ___addpadding-side">
                    <button name="update" class="button ___clear" type="submit">{% trans "Save" %}</button>
                </div>
            </div>

            <div class="card ___nopadding">
                <h2 class="card__title ___addpadding-side">{% trans "Avatar" %}</h2>
                <div class="account-user__pickavatar ___addpadding-side">
                    <div class="input-field">
                        {% if request.user.avatar %}
                            <img src="/media/{{ request.user.avatar }}" border=0 class="account-user__avatar">
                            <input id="avatar-clear_id" name="avatar-clear" type="checkbox">
                        {% else %}
                            <img src="/static/icons/person.svg" border=0 class="account-user__avatar">
                        {% endif %}

                        {{ form.errors.avatar }}
                        <input id="id_avatar" name="avatar" type="file" accept=".jpg, .jpeg, .png" onchange="this.form.submit()">
                     </div>
                    <button class="button" onClick="javascript:document.getElementById('id_avatar').click(); return false;">{% trans "Choose an avatar" %}</button>
                </div>
                <div class="card__action ___addpadding-side">
                    <button name="update" class="button ___clear" onClick="javascript:document.getElementById('avatar-clear_id').checked='true'; this.form.submit(); return false;">{% trans "Remove avatar" %}</button>
                </div>
            </div>
            <a href="{% url 'delete_account' %}" class="button ___clear ___error ___fullspan">
                {% trans "Delete my account" %}
            </a>
        </div>
    </form>

{% endblock %}

core/templates/register_activate.html
{% extends "base.html" %}
{% load i18n %}
{% load Pleio_templatetags %}

{% block page_title %}
{% trans "Activation error" %}
{% endblock %}

{% block content %}
    <h1 class="ui large header">{% trans "Activation error" %}</h1>
    <div class="messages ui error">
        <i class="icon" aria-hidden="true">{% include_asset "icons/account-alert.svg" %}<i>
        <div class="content">
            <div class="textcolor_primary">{% trans "We could not activate your account" %}</div>
            <div class="textcolor_secondary">{% trans "Your account may already be activated." %} </div>
        </div>
    </div>
    <a href="{% url 'login' %}" >{% trans "Return to sign in" %}</a>
{% endblock %}

core/templates/set_new_password.html
{% extends "base.html" %}
{% load i18n %}
{% load Pleio_templatetags %}
{% load settings_value %}


{% block content %}

<form method="post" action=".">
    {% csrf_token %}
    <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
    
    <div class="login__step-title">
        <div>
            <h2>{% trans "Welcome" %} {{ user.name }}</h2>
            <p>{% trans "Set the passsword for your new " %}{% settings_value 'SITE_TITLE' %}{% trans " account" %}</p>
        </div>
        <img src="/static/images/logo-icon.svg" class="login__step-icon"/>
    </div>
    
    <ul class="messages error">
            {% for error in form.non_field_errors %}
            <li>
                {% include_asset "icons/account-alert.svg" %}
                <div class="textcolor_primary">{% trans "Set password failed." %}</div>
                <div class="textcolor_secondary">{{ error }}</div>
            </li>
        {% endfor %}
    </ul>
    
    <fieldset>
        <div class="input-field">
            <label for="id_new_password1">{% trans "Password" %}</label>
            {{ form.errors.new_password1 }}
            {{ form.new_password1 }}
            <span class="password__toggle">{% include_asset "icons/eye.svg" %}</span>
            <p class="capslock"></p>
        </div>
        <div class="input-field">
            <label for="id_new_password2">{% trans "Password (again)" %}</label>
            {{ form.errors.new_password2 }}
            {{ form.new_password2 }}
            <span class="password__toggle">{% include_asset "icons/eye.svg" %}</span>
            <p class="capslock"></p>
        </div>

        <div class="register__buttons">
            <button name="set_password" class="button ___stretch ___active" type="submit">{% trans "Set password" %}</button>
        </div>
        
    </fieldset>
</form>

{% endblock %}